name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: ./
        with:
          branch: "master"
          message: ":boom: Testing"
          preserve-readme: true
          readme-file: "README.md"
          readme-message: "no problemo"
